services:
  # Backend API service
  - type: web
    name: receipt-splitter-backend
    runtime: python
    plan: free
    buildCommand: cd receipt-splitter-backend && pip install -r requirements.txt
    startCommand: cd receipt-splitter-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: PYTHONPATH
        value: .

  # Frontend static site
  - type: web
    name: bill-iant
    runtime: static
    buildCommand: cd receipt-splitter-frontend && npm install && npm run build
    staticPublishPath: ./receipt-splitter-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: receipt-splitter-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
